--- #YAML:1.0
name:                News-Search
version:             1.10
abstract:            Usenet news searching toolkit
license:             BSD
author:              
    - Tong Sun <suntong@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
